name: cinequizz
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  animated_flip_counter: ^0.3.4
  animations: ^2.0.11
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  circular_countdown_timer: ^0.2.4
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.15
  formz: 0.4.1 # do not update this
  fpdart: ^1.1.1
  get_it: ^8.0.2
  go_router: ^14.6.1
  google_sign_in: ^6.2.2
  introduction_screen: ^3.1.14
  just_audio: ^0.9.42
  liquid_progress_indicator_v2: ^0.5.0
  lottie: ^3.1.3
  lucide_icons: ^0.257.0
  material_dialogs: ^1.1.5
  random_avatar: ^0.0.8
  rxdart: ^0.28.0
  shadcn_ui: ^0.15.4
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  step_progress_indicator: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/core/generated/
  line_length: 80

  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app_logo.png"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  adaptive_icon_background: "#141414"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#141414"
  image: assets/images/app_logo.png
  branding: assets/images/app_logo.png
  branding_bottom_padding: 24
  color_dark: "#141414"
  image_dark: assets/images/app_logo.png
  branding_dark: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    icon_background_color: "#141414"
    image_dark: assets/images/app_logo.png
    icon_background_color_dark: "#141414"

  web: false
